In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [46]:
#create the dataset
X,y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=30)

In [47]:
X

array([[-2.26689933,  1.49959359,  0.75965452, ..., -0.74250649,
         1.0170277 , -1.45644926],
       [-1.28997309,  0.8331157 ,  0.41769573, ...,  0.2121813 ,
        -0.36359052, -0.83983932],
       [ 0.22216965,  1.38907741,  1.03319923, ...,  0.15190194,
         0.72825596,  0.98205686],
       ...,
       [ 0.20849575,  1.14820907,  0.85756747, ...,  1.11610857,
         0.00848992,  0.83671534],
       [-2.38812834, -0.34532195, -0.58792652, ..., -0.78802051,
        -0.22142448, -2.58624305],
       [ 0.04440334,  0.73896088,  0.53916948, ..., -0.75412292,
         0.30822932,  0.44835661]])

In [48]:
y

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,

In [49]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9
0,-2.266899,1.499594,0.759655,0.122765,-2.315735,-0.019930,-0.132149,-0.742506,1.017028,-1.456449
1,-1.289973,0.833116,0.417696,-0.284231,-1.066789,-0.073931,-0.026814,0.212181,-0.363591,-0.839839
2,0.222170,1.389077,1.033199,0.598068,0.384157,-0.217773,1.403139,0.151902,0.728256,0.982057
3,-1.266009,1.337652,0.784920,0.733756,-1.161272,-0.172708,0.211214,-0.424339,1.685622,-0.540096
4,-1.027363,0.667609,0.335617,0.250314,1.582328,0.121074,0.034026,0.948339,0.895196,-0.666628
...,...,...,...,...,...,...,...,...,...,...
995,0.027508,0.568849,0.414103,0.662608,-0.284284,-0.110962,-0.361262,0.493847,-0.551548,0.338443
996,2.143101,0.214668,0.458938,-1.087562,0.382458,-0.970834,0.288722,-0.843561,0.507008,2.268858
997,0.208496,1.148209,0.857567,-0.314116,-1.741188,0.967866,-0.632848,1.116109,0.008490,0.836715
998,-2.388128,-0.345322,-0.587927,-0.181420,0.206793,0.540870,0.431581,-0.788021,-0.221424,-2.586243


In [50]:
pd.DataFrame(y)

,0
0,1
1,1
2,1
3,1
4,1
...,...
995,1
996,0
997,1
998,0


In [51]:


from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X,y,test_size=0.30,random_state=42)

In [52]:

# Model training
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()

In [53]:
logistic_model.fit(train_X, train_y)

LogisticRegression()

In [54]:
y_pred_train = logistic_model.predict(train_X)
y_pred_test = logistic_model.predict(test_X)
print(y_pred_train)
print(y_pred_test)

[0 0 0 1 1 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 1
 1 1 0 0 0 0 1 0 1 1 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 1 0 0 1 0
 0 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 1
 1 0 1 0 0 1 0 1 1 0 1 1 1 1 0 0 1 0 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 1 1 0 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 0
 1 0 0 1 1 1 0 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0
 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 1 0 0 0 0 0 0
 0 1 1 0 0 0 1 1 0 0 1 1 0 1 1 1 1 0 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 0 1 1
 0 1 0 0 0 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 1 0 1 1 0 1 1 0 1
 0 0 1 0 1 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 1
 0 1 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 0 1 1
 0 1 0 0 0 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0
 1 0 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 1 0 0 1
 0 0 1 0 1 0 1 1 1 0 0 1 

In [55]:

logistic_model.predict_proba(test_X)

array([[7.87673616e-03, 9.92123264e-01],
       [9.77814619e-01, 2.21853806e-02],
       [1.41276008e-01, 8.58723992e-01],
       [8.50994153e-01, 1.49005847e-01],
       [1.11519008e-02, 9.88848099e-01],
       [7.81658668e-03, 9.92183413e-01],
       [3.32432595e-02, 9.66756741e-01],
       [7.91055405e-01, 2.08944595e-01],
       [9.99755712e-01, 2.44287772e-04],
       [9.99671341e-01, 3.28659260e-04],
       [5.81332640e-01, 4.18667360e-01],
       [6.68378776e-03, 9.93316212e-01],
       [8.91972797e-01, 1.08027203e-01],
       [9.72651622e-01, 2.73483776e-02],
       [3.63419805e-03, 9.96365802e-01],
       [4.12135097e-03, 9.95878649e-01],
       [1.84531990e-03, 9.98154680e-01],
       [1.89629261e-04, 9.99810371e-01],
       [9.32240556e-01, 6.77594439e-02],
       [6.90920396e-03, 9.93090796e-01],
       [1.78664398e-02, 9.82133560e-01],
       [4.20969177e-01, 5.79030823e-01],
       [9.93271847e-01, 6.72815339e-03],
       [3.77016955e-01, 6.22983045e-01],
       [9.870143

In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(train_y, y_pred_train))
print(accuracy_score(test_y, y_pred_test))

0.9257142857142857
0.9666666666666667


In [57]:
print(confusion_matrix(train_y, y_pred_train))
print('---------------------------------------')
print(confusion_matrix(test_y, y_pred_test))

[[342  19]
 [ 33 306]]
---------------------------------------
[[134   5]
 [  5 156]]


In [58]:
print(classification_report(train_y, y_pred_train))
print('---------------------------------------')
print(classification_report(test_y, y_pred_test))

              precision    recall  f1-score   support

           0       0.91      0.95      0.93       361
           1       0.94      0.90      0.92       339

    accuracy                           0.93       700
   macro avg       0.93      0.93      0.93       700
weighted avg       0.93      0.93      0.93       700

---------------------------------------
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       139
           1       0.97      0.97      0.97       161

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300



# Hyperparameter Tuning and Cross Validation


In [59]:

model = LogisticRegression()
penalty = ['l1', 'l2', 'elasticnet']
c_value= [100, 10 ,1.0, 0.1, 0.01]
solver = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

In [60]:
params = dict(penalty = penalty, C = c_value, solver = solver)

In [61]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()

In [62]:
## Grid Search CV
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=model, param_grid=params, scoring='accuracy', cv=cv, n_jobs=-1)

In [63]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [64]:
grid.fit(train_X, train_y)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solv

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [65]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [66]:
grid.best_score_

np.float64(0.9285714285714286)

In [68]:
y_pred = grid.predict(test_X)

In [69]:
print(accuracy_score(test_y, y_pred))

0.9666666666666667


In [71]:
print(confusion_matrix(test_y, y_pred))


[[134   5]
 [  5 156]]


In [73]:
print(classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96       139
           1       0.97      0.97      0.97       161

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300



# **Hyperparameter with Randomized Search**

In [74]:
from sklearn.model_selection import RandomizedSearchCV

In [76]:
model = LogisticRegression()
randomcv = RandomizedSearchCV(estimator = model, param_distributions=params, cv=5, scoring='accuracy')

In [77]:
randomcv.fit(train_X, train_y)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
30 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1203, in fit
    raise ValueError("l1_ra

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [78]:
randomcv.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 0.1}

In [79]:
randomcv.best_score_

np.float64(0.9257142857142856)

In [82]:
y_pred = randomcv.predict(test_X)

In [84]:
print(accuracy_score(test_y, y_pred))
print('--------------------------------------')
print(confusion_matrix(test_y, y_pred))
print('--------------------------------------')
print(classification_report(test_y, y_pred))

0.9666666666666667
--------------------------------------
[[134   5]
 [  5 156]]
--------------------------------------
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       139
           1       0.97      0.97      0.97       161

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300

